/**
 * parity.test.ts — cross-engine parity: the TypeScript engine must reproduce
 * the canonical Python engine.
 *
 * Fixtures are generated by `python -m tests.parity.generate_fixtures` (see
 * tests/parity/generate_fixtures.py) and committed as fixtures.json. Regenerate
 * them whenever the engine math changes on either side.
 *
 * Parity modes:
 *   - "exact"  — bit-for-bit equality (arithmetic, Threshold; the single
 *                OpenSimplex sample is also bit-identical across engines).
 *   - "approx" — equal to within a tight tolerance. Transcendentals (Sin, Cos,
 *                Log, Sqrt) differ in the last ULP between libm and V8, and
 *                multi-octave fBm diverges similarly (Python's
 *                `2 / 3**0.5` vs the TS `2 / Math.sqrt(3)`, plus summation
 *                rounding) — both ~1e-16, far below any real-bug threshold.
 *
 * KNOWN DIVERGENCE — Worley noise is intentionally NOT asserted here. The
 * Python kernel hashes cells with a 64-bit integer mix (matloom/engine/noise.py
 * `_hash_to_01`), while the TS port uses a 32-bit mix
 * (frontend/src/engine/noise.ts `hash01`), so feature-point placement differs.
 * The two Worley fields are statistically equivalent but not equal. See
 * AGENTS.md "Cross-engine parity" for the full note.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parseExpr } from "../../src/expr-lang/parser";
import { serializeExpr } from "../../src/expr-lang/serialize";
import {
  Color,
  Layer,
  evaluateMaterial,
  fBm,
  compositeHeight,
  heightToAo,
  heightToNormal,
} from "../../src/engine";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(
  readFileSync(join(here, "fixtures.json"), "utf8"),
) as {
  points: [number, number][];
  scalar: { src: string; mode: "exact" | "approx"; values: number[] }[];
  serialize: { src: string; serialized: string }[];
  shape_grid: { src: string; xs: number[]; ys: number[]; grid: number[] }[];
  fbm_grid: { seed: number; xs: number[]; ys: number[]; grid: number[] };
  relief: {
    height_composite: {
      xs: number[];
      ys: number[];
      layers: { alpha: string; height: string }[];
      grid: number[];
    };
    normal: {
      w: number;
      h: number;
      dx: number;
      dy: number;
      y_up: boolean;
      h_grid: number[];
      nx: number[];
      ny: number[];
      nz: number[];
    };
    ao: {
      w: number;
      h: number;
      dx: number;
      radius: number;
      strength: number;
      h_grid: number[];
      ao: number[];
    };
    ao_aniso: {
      w: number;
      h: number;
      dx: number;
      radiusX: number;
      radiusY: number;
      strength: number;
      h_grid: number[];
      ao: number[];
    };
    ao_fractional: {
      w: number;
      h: number;
      dx: number;
      radius: number;
      strength: number;
      h_grid: number[];
      ao: number[];
    };
    ao_fractional_aniso: {
      w: number;
      h: number;
      dx: number;
      radiusX: number;
      radiusY: number;
      strength: number;
      h_grid: number[];
      ao: number[];
    };
  };
  pbr: {
    program: string;
    w: number;
    h: number;
    y_up: boolean;
    pbr1: number[];
    pbr2: number[];
  };
};

// Tolerance for "approx" values: tight enough to catch a real bug, loose
// enough to permit last-ULP rounding differences (≈1e-16) between libm and V8
// in transcendentals and multi-octave fBm summation.
const APPROX_ATOL = 1e-11;

describe("scalar parity (Python -> TypeScript)", () => {
  for (const { src, mode, values } of fixtures.scalar) {
    it(`${mode}: ${src}`, () => {
      const expr = parseExpr(src);
      fixtures.points.forEach(([x, y], i) => {
        const got = expr.call(x, y);
        if (mode === "exact") {
          expect(got).toBe(values[i]);
        } else {
          expect(Math.abs(got - values[i])).toBeLessThan(APPROX_ATOL);
        }
      });
    });
  }
});

describe("serialization parity (identical canonical DSL)", () => {
  for (const { src, serialized } of fixtures.serialize) {
    it(src, () => {
      expect(serializeExpr(parseExpr(src))).toBe(serialized);
    });
  }
});

describe("shape grid parity", () => {
  // Feathered shape fields: the smooth coverage (and boundary behavior) the
  // 5-point scalar samples miss. Single-precision tolerance because the TS
  // path stores into a Float32Array.
  for (const { src, xs, ys, grid } of fixtures.shape_grid) {
    it(src, () => {
      const expr = parseExpr(src);
      const out = expr.evalGrid(
        Float32Array.from(xs),
        Float32Array.from(ys),
        xs.length,
        ys.length,
      );
      for (let i = 0; i < grid.length; i++) {
        expect(Math.abs(out[i] - grid[i])).toBeLessThan(1e-6);
      }
    });
  }
});

describe("fBm grid parity", () => {
  it("reproduces the Python fBm field at single-precision tolerance", () => {
    // The Python fixture computes the field in float64; the TS evalGrid path
    // accumulates in float64 but stores the result in a Float32Array, so the
    // comparison is at single-precision tolerance (~1e-6). This confirms the
    // gridded noise path tracks the reference, not just the scalar path.
    const { seed, xs, ys, grid } = fixtures.fbm_grid;
    const f = new fBm({ seed });
    const w = xs.length;
    const h = ys.length;
    const out = f.evalGrid(Float32Array.from(xs), Float32Array.from(ys), w, h);
    for (let i = 0; i < grid.length; i++) {
      expect(Math.abs(out[i] - grid[i])).toBeLessThan(1e-6);
    }
  });
});

describe("relief parity (height -> normal / AO)", () => {
  // Single-precision tolerance: the TS engine derives relief in Float32 while
  // the Python reference uses float64.
  const RELIEF_ATOL = 1e-5;

  it("composites per-layer heights with maxᵢ { hᵢ : αᵢ > 0 }", () => {
    const { xs, ys, layers, grid } = fixtures.relief.height_composite;
    const fx = Float32Array.from(xs);
    const fy = Float32Array.from(ys);
    const w = xs.length;
    const h = ys.length;
    const alphaGrids = layers.map((l) =>
      parseExpr(l.alpha).evalGrid(fx, fy, w, h),
    );
    const heightGrids = layers.map((l) =>
      parseExpr(l.height).evalGrid(fx, fy, w, h),
    );
    const out = compositeHeight(alphaGrids, heightGrids);
    for (let i = 0; i < grid.length; i++) {
      expect(Math.abs(out[i] - grid[i])).toBeLessThan(RELIEF_ATOL);
    }
  });

  it("derives the OpenGL normal from a height field", () => {
    const { w, h, dx, dy, y_up, h_grid, nx, ny, nz } = fixtures.relief.normal;
    const {
      nx: gx,
      ny: gy,
      nz: gz,
    } = heightToNormal(Float32Array.from(h_grid), w, h, dx, dy, y_up);
    for (let i = 0; i < nx.length; i++) {
      expect(Math.abs(gx[i] - nx[i])).toBeLessThan(RELIEF_ATOL);
      expect(Math.abs(gy[i] - ny[i])).toBeLessThan(RELIEF_ATOL);
      expect(Math.abs(gz[i] - nz[i])).toBeLessThan(RELIEF_ATOL);
    }
  });

  it("derives the AO map from a height field", () => {
    const { w, h, dx, radius, strength, h_grid, ao } = fixtures.relief.ao;
    const out = heightToAo(
      Float32Array.from(h_grid),
      w,
      h,
      dx,
      radius,
      strength,
    );
    for (let i = 0; i < ao.length; i++) {
      expect(Math.abs(out[i] - ao[i])).toBeLessThan(RELIEF_ATOL);
    }
  });

  it("derives an anisotropic AO map (per-axis blur radius)", () => {
    const { w, h, dx, radiusX, radiusY, strength, h_grid, ao } =
      fixtures.relief.ao_aniso;
    const out = heightToAo(
      Float32Array.from(h_grid),
      w,
      h,
      dx,
      radiusX,
      strength,
      radiusY,
    );
    for (let i = 0; i < ao.length; i++) {
      expect(Math.abs(out[i] - ao[i])).toBeLessThan(RELIEF_ATOL);
    }
  });

  it("derives a fractional-radius AO map (continuous crop zoom)", () => {
    const { w, h, dx, radius, strength, h_grid, ao } =
      fixtures.relief.ao_fractional;
    const out = heightToAo(
      Float32Array.from(h_grid),
      w,
      h,
      dx,
      radius,
      strength,
    );
    for (let i = 0; i < ao.length; i++) {
      expect(Math.abs(out[i] - ao[i])).toBeLessThan(RELIEF_ATOL);
    }
  });

  it("derives a fractional anisotropic AO map (per-axis fractional radius)", () => {
    const { w, h, dx, radiusX, radiusY, strength, h_grid, ao } =
      fixtures.relief.ao_fractional_aniso;
    const out = heightToAo(
      Float32Array.from(h_grid),
      w,
      h,
      dx,
      radiusX,
      strength,
      radiusY,
    );
    for (let i = 0; i < ao.length; i++) {
      expect(Math.abs(out[i] - ao[i])).toBeLessThan(RELIEF_ATOL);
    }
  });
});

describe("OpenPBR channel parity (packed pbr1 / pbr2 maps)", () => {
  // The six OpenPBR channels (sheen/coat/transmission/ior/subsurface/anisotropy)
  // composite with the same alpha-weighted over-blend as metallic/roughness and
  // pack into two RGBA8 maps. Byte quantization is integer-valued, so the maps
  // must match the Python reference EXACTLY (no tolerance) — earlier fixtures
  // covered none of these channels. The layers below mirror the program in
  // tests/parity/generate_fixtures.py `_pbr_fixtures` (built directly from the
  // channel field expressions, like test/eval/eval-core.test.ts).
  it("reproduces the Python pbr1 / pbr2 packing byte-for-byte", () => {
    const { w, h, pbr1, pbr2 } = fixtures.pbr;
    const E = (s: string) => parseExpr(s);
    const layers = [
      new Layer({
        alpha: E("1"),
        basecolor: new Color({
          r: E("120 / 255"),
          g: E("120 / 255"),
          b: E("120 / 255"),
        }),
        metallic: E("0.2"),
        roughness: E("0.5"),
        sheen: E("0.1"),
        coat: E("0.2"),
        transmission: E("0.3"),
        ior: E("1.4"),
        subsurface: E("0.4"),
        anisotropy: E("0.5"),
      }),
      new Layer({
        alpha: E("Threshold(X(), below_at=0.4, above_at=0.6)"),
        basecolor: new Color({
          r: E("200 / 255"),
          g: E("50 / 255"),
          b: E("50 / 255"),
        }),
        roughness: E("Y()"),
        sheen: E("X()"),
        coat: E("(X() * Y())"),
        transmission: E("0.7"),
        ior: E("2.0"),
        subsurface: E("Y()"),
        anisotropy: E("(1 - X())"),
      }),
    ];
    const maps = evaluateMaterial(layers, w, h, { yUp: true });
    expect(Array.from(maps.pbr1)).toEqual(pbr1);
    expect(Array.from(maps.pbr2)).toEqual(pbr2);
  });
});
