"""Golden byte gate for ``fixed_light_preview`` at 256 — the committed CI
counterpart of the dev-machine fingerprint harness. Pins sha256(tobytes +
shape + dtype) for the 10 slowest corpus programs of the baseline bench plus 2
Define/Rotate-heavy ones (programs copied verbatim into
``tests/data/golden_programs/``; provenance in
``/tmp/preview_bench/corpus_manifest.json`` at capture time). numpy and numba
are unpinned in requirements-test.txt, so a CI install on a different version
pair may legitimately produce different bytes: the test skips there instead of
flaking (the runtime-oracle tests in ``test_noise.py`` — kernel vs scalar
``__call__`` / legacy numpy loop — are the version-robust exactness gate). When
the version pair moves, re-render the golden set on the new pair and commit the
new digests only after the 0-ulp oracles still pass."""

import hashlib
from pathlib import Path

import numba
import numpy as np
import pytest

from matloom.engine.main import LayeredMaterial
from matloom.engine.preview import fixed_light_preview

_SIZE = 256
_GOLDEN_DIR = Path(__file__).resolve().parent.parent / "data" / "golden_programs"

# Byte stability of the numba/numpy stack is only guaranteed per version pair.
# Each listed pair has been verified to produce the digests below: the dev
# capture env (numpy 2.4.6 + numba 0.65.1) and a fresh py3.10
# requirements-test.txt install (numpy 2.2.6 + numba 0.67.0, what CI's 3.10
# leg resolves today), so the gate executes there instead of skipping.
_RECORDED_VERSIONS = (("2.4.6", "0.65.1"), ("2.2.6", "0.67.0"))

pytestmark = pytest.mark.skipif(
    (np.__version__, numba.__version__) not in _RECORDED_VERSIONS,
    reason=(
        f"golden bytes were recorded on the numpy/numba pairs "
        f"{_RECORDED_VERSIONS}, this env runs numpy {np.__version__} + numba "
        f"{numba.__version__}; the runtime-oracle tests in test_noise.py "
        "remain the version-robust gate"
    ),
)

# Digests of fixed_light_preview(material, 256, 256): sha256 over
# arr.tobytes() + f"{arr.shape}{arr.dtype}", generated by
# /tmp/preview_bench/make_golden.py and cross-checked against the
# 582-fingerprint baseline (pure-tobytes sha) at generation time.
_GOLDEN_256 = {
    "traj__slate_20260909-121531-127913__program_4.dsl": "fbfe6dd29529b0db0b4da1215c0f45b2ced45cda0e08e1aa7cdd0ba767a551c7",
    "traj__slate_20260909-121531-127913__program_5.dsl": "c5faa104936591b60d0794d85c2f7c6d7f3e059bc0fe7582d919c579996d5600",
    "traj__slate_20260909-121531-127913__program_6.dsl": "d05c6760a6c898bf99233c6b792e97d81a6991295c868922405f9115ae73ea36",
    "traj__slate_20260909-133024-853036__program_4.dsl": "2bcb9e83d96cd6e86ef0628a6b31a82618b2c3fdf8d9345d98e305018277488d",
    "traj__slate_20260909-133024-853036__program_5.dsl": "1e8683ce410a68c6c2826ade70bcec7b27dbdb71355ccdbe6f68e08c9008f8e6",
    "traj__slate_20260909-141834-014373__program_1.dsl": "fce52d84bb5d0b294a3adfc384a0e3ce81859fe466254726287d898448cc7ee7",
    "traj__slate_20260909-141834-014373__program_2.dsl": "2c55cbaa1bdf38a9f2a8ff88bff7daeecba569334d076f021dfb5556aa08a606",
    "traj__slate_20260909-141834-014373__program_3.dsl": "4e5befa47f4c61853dea5f73b030387ec37459e295ab5154c0572c8fb36ef132",
    "traj__slate_20260909-141834-014373__program_4.dsl": "bdbf0eb6866666d72e28bf40d458a2667fc17b5ef877136d38e0ede9c75ed392",
    "traj__slate_20260909-141834-014373__program_5.dsl": "8dbb78f329f63aa3ec932a52887f40c9c23878caa3d0e955730f4cc9f679324c",
    "traj__slate_20260909-141853-147994__program_4.dsl": "d44a64937b652d0b3f3f7966303cf8e944d84e6a78f0f56a263b8f34428af2dc",
    "traj__slate_20260909-141853-147994__program_5.dsl": "dbe6e01415944bcf3c71514470c2a3da9ab3c65d4d72d76a759ae5f2a8cc1d06",
}


def _digest(arr: np.ndarray) -> str:
    h = hashlib.sha256()
    h.update(arr.tobytes())
    h.update(f"{arr.shape}{arr.dtype}".encode())
    return h.hexdigest()


@pytest.mark.parametrize("name,digest", sorted(_GOLDEN_256.items()))
def test_golden_preview_256(name: str, digest: str) -> None:
    material = LayeredMaterial.deserialize((_GOLDEN_DIR / name).read_text())
    arr = fixed_light_preview(material, _SIZE, _SIZE)
    assert arr.dtype == np.uint8
    assert arr.shape == (_SIZE, _SIZE, 3)
    assert _digest(arr) == digest
